hash-format = "sha256"

[[files]]
file = "config/Obscuria/obscure-api-client.toml"
hash = "ffe4aeb7bd9c696e24f0cd0bc75c84fb92ed9d9a9236b4742d612652b4b127ce"

[[files]]
file = "mods/aether.pw.toml"
hash = "1aaba088a650cc1499e1871cfa92f97e3d10a9d8c612fbd784b36c12382196de"
metafile = true

[[files]]
file = "mods/alshanexs-familiars.pw.toml"
hash = "7e48e349828f7f9f1cf9a58f9bb80be56c4f109398ed5a2ed3e23b93fa0cd550"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/aquamirae-delight.pw.toml"
hash = "297741da12bec38296771e1840245a257fa20bbb228cdc89d3b6507a565476ee"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "61108f6f38c397683bcf3e9fab0641819ea6914a5b95e6a31fcdbf55466c2e26"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/baubley-heart-canisters.pw.toml"
hash = "72390c72a1091cd347aad048d125b47efff3d1ed90f7bc6126cb2e3f85437f53"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "2bcea8e16d358942a8f8b8cf6e39cc303d90fac29b1b3ecb8033bd214d4afa0f"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
hash = "832ce23a285dd86387eb7950f6159cc0ec0cdda36dad4b7036c35a99001b6943"
metafile = true

[[files]]
file = "mods/braziliandelight.pw.toml"
hash = "924b4ac60309e954432ab122566d6931418fbbd6da3804eef64632f245a10924"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "8a8ea0af79b88d9c192d208aa5be4bacd934e2b92d4721566e2e796eb9761e10"
metafile = true

[[files]]
file = "mods/constructs-casting.pw.toml"
hash = "b70c41760bf939271b0d6a41f54b0f5a9e66f02cc3c9329722216bec908f380c"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "d42c60a8b8191af3bb9f37b85e7b28ff73cb7bc513dae1b3391ce0a8b26ebad4"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "6292625ed60e17068f3e7927d26c75053b64269c922f10b1c87ceea51ccb194e"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
hash = "6921e786ec0f9d1a782455b815c84aca210f26173756a357a26c32d0866e74dc"
metafile = true

[[files]]
file = "mods/deltaboxlib.pw.toml"
hash = "3605597ba3c20ae649d26cb82b8d4e365fd01d5f5e199e88bde0137d94a2b10f"
metafile = true

[[files]]
file = "mods/dungeons_delight.pw.toml"
hash = "5a9c0b4bb162a8edfd2541b4d30e691b98e389068e5a9c6f9d9b4248ad7a5044"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "3f63f54bf638954d1da79cacc7ab2d58e1886c98bdb2b267035abfa0ce8a5a72"
metafile = true

[[files]]
file = "mods/evilcraft.pw.toml"
hash = "464eb120923c99c1aacd8f7312617fe7468b9c52ab341907b6ae80d32d569b7c"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/forge-config-screens.pw.toml"
hash = "50ec52c5c84ffb604eacdd19b27a5660f6f2e8365b168f108b68a6ccc96fa8ee"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/ghost.pw.toml"
hash = "a210731d0c29fc5676d872d038ad7250b0d0d41e49957ad9dfb3bd8bc484e1c5"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/guide-api.pw.toml"
hash = "17b826d2504d643fe7df27f4448ea30b5e99c49bc2aaa1dd08c153be32a893e6"
metafile = true

[[files]]
file = "mods/irons-rpg-tweaks.pw.toml"
hash = "2037eddce294977b36ff8cd1dc7c7cdc5f772b6516853a320444f9f14c2863e6"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "d8c354de7ab3aef949b8f8598ae57f07f1a38711d99588f27b93c1af93a14fba"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "f8312021fd88a4952e1d50a2f156fab65314f87658d7153efc56be76a422d5cd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "dbd137b861d4c78ca28a1a95a7df72b6f3f0d9cd13a31ae6eed0986094a7924b"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "adb67ada5c165ea4a43f4c3e53ffd61c90e21292596b5609d97e938f6e8e7b16"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "fc09447db9efb9f9ec998ce84cf11edfd089a2515a300e45fd06e607aabc051a"
metafile = true

[[files]]
file = "mods/my-nethers-delight.pw.toml"
hash = "019b1fc9ddc90219203532bf68538e1f1b2487599c6c9b9a3a074df0abd66b48"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "70d4e3ec754f6fffc5bd03814ed7e7a137b83311a43c817eef2fb2ac9c417d27"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "55c6d0b8ee25fd6a37a964805de3d2eab3f20d73a88ba77a63b4a51fd985d9dd"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "765987a78e5d8c782d0da2de99998b43b5907d6c41347d3804045ad109e4a586"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b85e8417e797be3fdae046c487eeda8f54cdc88f3f20e462e0e229f8dd734214"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "d668582ea913944b31fda3e0cbe8bd7fda3852f960bd4f7a58fe9bba526a9037"
metafile = true

[[files]]
file = "mods/runiclib.pw.toml"
hash = "2dbe8c4d2e526717bb37fca847e0d7e42c2f65575e90883b096a2cd2787ccb30"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "e63ae372407e332a7eff9365443685c0662f185eab65ca849d5306675d698c44"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
hash = "25e0793ab87d3b02131b8570982d485d5680f95df2455672e0bc2082b03b3ea9"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/the-aethers-delight.pw.toml"
hash = "9e42e106415a4fe07bdfe23d1470c81cb924c03c95ead8fd9d1216701ab67b12"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "6160cdcd8b686e90f72e76072ba96de7c5ae40460b3771401222ddebdee1d5ed"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "6a249583abaec5492b693b8a19e1b42abb338af6517f92004c86471df57ddfc0"
metafile = true

[[files]]
file = "mods/vampires-delight.pw.toml"
hash = "f83e994c609617a35141e64af1632a3a53434ee143e2700ccb122159375d05bb"
metafile = true

[[files]]
file = "mods/vampires-need-umbrellas.pw.toml"
hash = "7dbcf96055074145dee5398deda1c48ca902302eb773539b33cddf64c442335a"
metafile = true

[[files]]
file = "mods/vampirism-integrations.pw.toml"
hash = "e9ea8b414553c57cb83c68c1ba207c2a9f8c5d5a13f86a2e65c44b1c62b8b892"
metafile = true

[[files]]
file = "mods/vampirism.pw.toml"
hash = "83182dcb7e4463e5e2ceefa544e3a6d0b427e4637d5bef613a632bed39731c0d"
metafile = true

[[files]]
file = "mods/werewolves.pw.toml"
hash = "2f13dc11c0d7bd59bed4a50874668d6e60c4de6c3be467416e01af652cb5a011"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1a592e56f6720b44d1031d2d715d454eff2099e915160c0c75f853ae8b314b15"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7e7b7624e041a1364971057d1c47f2b74730e191f142b73aa50223f95978dd96"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true
