name = "Modsa"
author = "Ian"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14241dcfe5623eeed7f623b44caa844c45cd7f92755f74befb2ed0e5929d2033"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
