name = "Modsa"
author = "Ian"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62a799ed19c56fd0ce03db88c4996261d5d2528e2adab4e046fc4e2eadd6f87e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
